services:
  app_router:
    image: caddy:latest
    container_name: app_router
    restart: unless-stopped
    environment:
      - WEBUI_HOST=${WEBUI_HOST}   # Used for self referenced responses
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    ports:
      - "127.0.0.1:80:80"          # HTTP (for automatic rediret)
      - "127.0.0.1:443:443"        # HTTPS (TCP)
      - "127.0.0.1:443:443/udp"    # HTTP/3 (UDP) - to be used only if Caddy is configured to support HTTP/3, otherwise can be removed
    volumes:
      - app_wasm_artifact:/usr/share/caddy:ro # Shared app artifacts (static files)
      - ./.container/router/Caddyfile:/etc/caddy/Caddyfile
      - router_caddy_data:/data
      - router_caddy_config:/config
    networks:
      - app_network
    depends_on:
      - app_api

  app_api:
    image: rust:${RUST_VER}-slim
    container_name: app_api
    working_dir: /usr/src/app
    environment:
      - CARGO_TARGET_DIR=/cargo_target # Forces cargo target dir to be out of the api dir
      - CARGO_TERM_COLOR=always
      - WEBUI_HOST=${WEBUI_HOST}       # Used for app referenced responses
      - API_HOST=${API_HOST}           # Used for self referenced responses, internally bound to 0.0.0.0 (lisen on all interfaces)
      - API_PORT=${API_PORT}
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    volumes:
      - ./api:/usr/src/app
      - ./proto:/usr/src/proto:ro # Shared proto artifacts (generated code)
      - app_api_cargo_cache:/usr/local/cargo/registry
      - app_api_rust_target:/cargo_target
    networks:
      - app_network
    command: >
      sh -c "apt-get update && apt-get install -y protobuf-compiler libprotobuf-dev &&
      cargo install cargo-watch &&
      cargo watch -x run"

  # [!TIP] app_artifact_builder service is needed to hot reload the frontend app into the router container
  app_wasm_artifact_builder:
    image: rust:${RUST_VER}-slim
    container_name: app_wasm_artifact_builder
    working_dir: /usr/src/app
    environment:
      - CARGO_TARGET_DIR=/cargo_target # Forces cargo target dir to be out of the app dir
      - CARGO_TERM_COLOR=always
    volumes:
      - ./app:/usr/src/app
      - ./proto:/usr/src/proto:ro      # Shared proto artifacts (generated code)
      - app_wasm_artifact:/artifact_pkg
      - app_wasm_artifact_builder_cargo_cache:/usr/local/cargo/registry
      - app_wasm_artifact_builder_rust_target:/cargo_target
    command: >
      sh -c "apt-get update && apt-get install -y protobuf-compiler libprotobuf-dev binaryen &&
      cargo install wasm-pack cargo-watch &&
      cargo watch -i 'pkg/*' -s 'wasm-pack build --target web --dev --out-dir /artifact_pkg/wasm && cp index.html /artifact_pkg/'"
    # Note: for production should be used 'wasm-pack build --target web --release' instead of '--dev' to get optimized .wasm files

networks:
  app_network:
    driver: bridge

volumes:
  router_caddy_data:
  router_caddy_config:
  app_api_cargo_cache:  
  app_api_rust_target:  
  app_wasm_artifact_builder_cargo_cache:  
  app_wasm_artifact_builder_rust_target:
  app_wasm_artifact:
